export interface excelImportRow {
	record_id: string
	redcap_data_access_group: string
	redcap_event_name: string
	birthdate: number
	sex: number
	height: number
	weight: number
	charlson_stroke: number
	charlson_dementia: number
	charlson_myocardial: number
	charlson_heartfailure: number
	charlson_peripheral_vd: number
	charlson_copd: number
	charlson_tissue: number
	charlson_peptic: number
	charlson_liver: number
	charlson_diabetes: number
	charlson_hemiplegia: number
	charlson_ckd: number
	charlson_malignancy: number
	charlson_leukaemia: number
	charlson_lymphoma: number
	charlson_aids: number
	charlson_score: number
	icuadm_cfs: string
	apache_score_c: number
	hospadm_date_time: Date
	icuadm_date_time: Date
	diagnosis_resp: string
	diagnosis_cardiac: string
	ecmo_start_date_time: Date
	decan_date_time: Date
	outcm_icu_discharge: Date
	outcm_hosp_discharge: Date
	outcm_hosp_discharge_loc: string
	outcm_ecmo_days_2: number
	outcm_icu_days: number
	outcm_hosp_days: number
}
