export const ARDS_COMPLICATIONS_MAP: Record<string, string> = {
	form11_mech_oxygenator: "Oxygenator failure",
	form11_mech_pump: "Pump failure",
	form11_mech_problem: "Cannula problems",
	form11_mech_air: "Air in circuit",
	form11_mech_gas: "Disruption of gas flow to ECMO circuit",
	form11_mech_heat: "Heat exchanger malfunction",
	form11_mech_thromb: "Thrombosis/Clots: Circuit component",
	form11_mech_clot: "Clots in haemofilter",
	form11_haem_hemorrhage: "GI haemorrhage",
	form11_haem_peripheral: "Peripheral cannulation site bleeding",
	form11_haem_mediastinal: "Mediastinal cannulation site bleeding",
	form11_haem_surgical: "Surgical site bleeding",
	form11_haem_major: "Major bleeding",
	form11_renal_132: "Creatinine 132 - 265\u03bcmol/L (1.5 - 3.0)",
	form11_renal_265: "Creatinine >265\u03bcmol/L (>3.0)",
	rrt: "CRRT",
	form11_cardio_cpr: "Cardiac arrest",
	form11_cardio_arrhythmia: "Cardiac arrhythmia",
	form11_cardio_tamponade: "Tamponade (not blood)",
	form11_cardio_tamponadeb: "Tamponade (blood)",
	form11_cardio_ami: "Acute myocardial infarction",
	form11_cardio_lvd: "Left ventricle distension",
	form11_cardio_uvf_2: "Unanticipated ventricle fibrillation",
	form11_cardio_clot: "Intracardiac/aortic clot",
	form11_pulmonary_pneum: "Pneumothorax",
	form11_pulmonary_pulh: "Pulmonary haemorrhage",
	form11_pulmonary_pule: "Pulmonary embolism",
	form11_metabolic_bili: "Hyperbilirubinemia",
	form11_metabolic_heamm: "Moderate haemolysis",
	form11_metabolic_heams: "Severe haemolysis",
	form11_metabolic_hypox: "Patient hypoxia",
	form11_metabolic_hypoxd: "Differential hypoxia",
	form11_limb_fasciotomy: "Fasciotomy",
	form11_limb_pressure: "Pressure injury",
	form11_limb_amputation: "Limb amputation",
	form11_limb_ischemia: "Limb ischaemia requiring limb reperfusion cannula",
	form11_limb_dvt: "Deep vein thrombosis ",
	form11_limb_hyperfusion: "Limb hyper-perfusion",
	form11_limb_comp: "Limb Compartment Syndrome",
	form11_neuro_bd: "Brain death",
	form11_neuro_seizure: "Seizures clinically determined",
	form11_neuro_seizuree: "Seizures confirmed by EEG",
	form11_neuro_cnsisc: "CNS diffuse ischaemia ",
	form11_neuro_cnsinf: "CNS Infarction OR thrombotic / embolic CVA",
	form11_neuro_ich: "Intracranial Haemorrhage (ICH) ",
	form11_neuro_intervention: "Neurosurgical intervention performed",
	form11_inf_can: "Cannula site infection",
	form11_inf_blood: "Blood stream infection",
	form11_inf_lung: "Lung infection",
	form11_inf_other: "Other infection",
}
